stages:          
  - build
  - test

build job:      
  stage: build
  script:
    - mkdir /home/gitlab-runner/builds/build
    - touch /home/gitlab-runner/builds/build/info.txt
    - echo "Compile complete."
  tags:
    - netology
      
unit test:  
  stage: test    
  script:
    - echo "Testing"
    - test -f /home/gitlab-runner/builds/build/info.txt && echo "$FILE Существует"
  tags:
    - netology