---
apiVersion: v1
kind: Deployment
metadaa:
  name: netology-ml
spec:
  replicas: 2
  strategy:
    rollingUpdates:
      maxSurge: 1
      maxUnavaible: 1
    type: RollingUpdate
    template:
      metadata:
        labels:
          app: netology-ml
      spec:
        containers:
          - image: tomcat:8.5.69
            name: tomcat
            ports:
              - containerPort:8080